In [53]:
import torch
import numpy as np

In [70]:
t1 = torch.tensor([1,2,3,4,5,6])
t2 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
t3 = torch.tensor([[7,8],[9,10],[11,12]])
t3

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [26]:
t2.shape

torch.Size([1, 3, 3])

In [27]:
t2 = torch.reshape(t2, (3,3))
t2.shape

torch.Size([3, 3])

In [28]:
t1 = t1.view((3,2))
t1

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [32]:
stack_0 = torch.stack((t1,t3))
stack_0

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [33]:
stack_1 = torch.stack((t1,t3), dim=1)
stack_1

tensor([[[ 1,  2],
         [ 7,  8]],

        [[ 3,  4],
         [ 9, 10]],

        [[ 5,  6],
         [11, 12]]])

In [37]:
stack_0 = stack_0.view((1,6,2))
stack_0

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [39]:
stack_0 = torch.squeeze(stack_0)
stack_0.shape

torch.Size([6, 2])

In [42]:
unsq = torch.unsqueeze(t1, 0)
unsq.shape

torch.Size([1, 3, 2])

In [50]:
print(stack_1.shape)
print(torch.permute(stack_1, (2,0,1)).size())

torch.Size([3, 2, 2])
torch.Size([2, 3, 2])


In [52]:
print(stack_0[3][1], stack_0[1][0])

tensor(8) tensor(3)


In [57]:
a = np.array([1,1,2,3,5,8])
ten_np = torch.from_numpy(a)
print(ten_np)
b = ten_np.numpy()
print(b)

tensor([1, 1, 2, 3, 5, 8])
[1 1 2 3 5 8]


In [59]:
rand = torch.rand((7,7))

In [61]:
rand_1 = torch.rand((1,7))
mul = torch.matmul(rand_1, rand)
mul.shape

torch.Size([1, 7])

In [63]:
torch.cuda.is_available()

False

In [64]:
t1 = torch.rand((2,3))
t2 = torch.rand((2,3))

In [65]:
t8 = torch.matmul(t1, t2.reshape((3,2)))
t8.shape

torch.Size([2, 2])

In [67]:
print(torch.max(t1))
print(torch.min(t2))

tensor(0.8204)
tensor(0.4741)


In [68]:
print(torch.argmax(t1))
print(torch.argmin(t2))

tensor(0)
tensor(3)


In [69]:
torch.manual_seed(7)

In [73]:
t10 = torch.rand((1,1,1,10))
print(t10)
print(t10[0])

tensor([[[[0.8829, 0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286,
           0.7653, 0.1132]]]])
tensor([[[0.8829, 0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286,
          0.7653, 0.1132]]])
