In [43]:
import numpy as np

### Q1

In [44]:
arr_1d = np.arange(9)
print(f'1D array: {arr_1d}')

1D array: [0 1 2 3 4 5 6 7 8]


In [45]:
arr_2d = np.reshape(arr_1d, (3,3))
print(f'2D array:\n {arr_2d}')

2D array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


## Q2

In [46]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
arr[arr%2 == 1] = -1
print(f'Array with odd numbers replaced by -1 : {arr}')

Array with odd numbers replaced by -1 : [ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Q3

In [48]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(f'x: {x}\ny:{y}')

x: [21 64 86 22 74 55 81 79 90 89]
y:[21  7  3 45 10 29 55  4 37 18]


In [49]:
xGy = np.nonzero(x>y)[0]
print(f'Indices where x>y: {xGy}')
xEy = np.nonzero(x==y)[0]
print(f'Indices where x=y: {xEy}')

Indices where x>y: [1 2 4 5 6 7 8 9]
Indices where x=y: [0]


## Q4

In [50]:
a = np.arange(100).reshape((5,-1))
print(f'a:\n{a}')
print(f'First 4 columns:\n{a[:,:4]}')

a:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
First 4 columns:
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


## Add 1

In [51]:
random_arr = np.random.randint(30, 41, size=10)
print(f'Random array between 30 and 40: {random_arr}')

Random array between 30 and 40: [33 34 36 30 35 33 34 33 32 39]


## Add 2

In [52]:
A = np.array((1, 2, 3, 4, 5, 6, 7, 8, 10)).reshape(3,3)
B = np.array((7, 8, 10, 4, 5, 6, 1, 2, 3)).reshape(3,3)
print(f'A:\n{A}')
print(f'B:\n{B}')

A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
B:
[[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]


In [53]:
C = A+B
E = A-B
print(f'C:\n{C}')
print(f'E:\n{E}')

C:
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
E:
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [54]:
print(f'Sum of elements of A: {np.sum(A)}')
print(f'Sum of column of B: {np.sum(B, axis=0)}')
print(f'Sum of rows of C: {np.sum(C, axis=1)}')

Sum of elements of A: 46
Sum of column of B: [12 15 19]
Sum of rows of C: [31 30 31]


In [55]:
D = A*B
print(f'D:\n{D}')

D:
[[ 7 16 30]
 [16 25 36]
 [ 7 16 30]]


In [56]:
E = np.sort(C, axis=0)
print(f'E:\n{E}')

E:
[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]


In [57]:
E = np.transpose(E)
print(f'Transposed E:\n{E}')

Transposed E:
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]
